"""fix users id

Revision ID: 76bbd2115a9e
Revises: fd542e27084c
Create Date: 2026-10-02 01:37:11.015213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76bbd2115a9e'
down_revision: Union[str, Sequence[str], None] = 'fd542e27084c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE public.users ALTER COLUMN id "
        "ADD GENERATED BY DEFAULT AS IDENTITY"
    )

    # Добавь эту строку, только если запрос выше НЕ нашёл первичный ключ:
    op.create_primary_key("users_pkey", "users", ["id"])

    # Если в таблице уже были пользователи, следующий ID
    # должен быть больше существующих:
    op.execute("""
        SELECT setval(
            pg_get_serial_sequence('public.users', 'id'),
            COALESCE((SELECT MAX(id) FROM public.users), 0) + 1,
            false
        )
    """)


def downgrade() -> None:
    """Downgrade schema."""
    pass
